// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#ifndef _NEW_UI_H
#define _NEW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen_1_Main.h"
#include "ui_Screen_2_Setting.h"
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_backgroundlight_png);    // assets/backgroundlight.png
LV_IMG_DECLARE(ui_img_btn_main_png);    // assets/btn_main.png
LV_IMG_DECLARE(ui_img_btn_setting_png);    // assets/btn_setting.png
LV_IMG_DECLARE(ui_img_btn_print_down_png);    // assets/btn_print_down.png
LV_IMG_DECLARE(ui_img_btn_print_top_off_png);    // assets/btn_print_top_off.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_pot_slider_png);    // assets/pot_slider.png
LV_IMG_DECLARE(ui_img_btn_main_off_png);    // assets/btn_main_off.png
LV_IMG_DECLARE(ui_img_btn_main_on_png);    // assets/btn_main_on.png
LV_IMG_DECLARE(ui_img_btn_minus_png);    // assets/btn_minus.png
LV_IMG_DECLARE(ui_img_btn_up_png);    // assets/btn_up.png
LV_IMG_DECLARE(ui_img_btn_pattern_png);    // assets/btn_pattern.png
LV_IMG_DECLARE(ui_img_noimage_png);    // assets/noimage.png
LV_IMG_DECLARE(ui_img_icn_bed_png);    // assets/icn_bed.png
LV_IMG_DECLARE(ui_img_icn_stop_png);    // assets/icn_stop.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Small_Font);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font22);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
