// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Display_Heat_S2 = NULL;
lv_obj_t * ui_DT3 = NULL;
lv_obj_t * ui_Label_Printing_Head_Temp3 = NULL;
lv_obj_t * ui_Label_Head_Temp2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_DT3_copy3 = NULL;
lv_obj_t * ui_Label_Printing_Bed_Temp5 = NULL;
lv_obj_t * ui_IMG_Head2 = NULL;
lv_obj_t * ui_Label_Bed_Temp4 = NULL;
lv_obj_t * ui_Label_Printing_Bed_Temp1 = NULL;
lv_obj_t * ui_Swich_Group2 = NULL;
lv_obj_t * ui_Label_Light2 = NULL;
lv_obj_t * ui_Switch_Light2 = NULL;
lv_obj_t * ui_Label_Fan_7 = NULL;
lv_obj_t * ui_Switch_Fan_7 = NULL;
lv_obj_t * ui_Label_Fan_4 = NULL;
lv_obj_t * ui_Switch_Fan_4 = NULL;
lv_obj_t * ui_Label_Fan_5 = NULL;
lv_obj_t * ui_Switch_Fan_5 = NULL;
lv_obj_t * ui_BTN_Cancel3 = NULL;
lv_obj_t * ui_BTN_Cancel_Top3 = NULL;
lv_obj_t * ui_Image_Cancel3 = NULL;
// event funtions
void ui_event_BTN_Cancel_Top3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_BTN_Pause_Top, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Display_Heat_S2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Display_Heat_S2, 350);
    lv_obj_set_height(ui_Display_Heat_S2, 79);
    lv_obj_set_x(ui_Display_Heat_S2, -322);
    lv_obj_set_y(ui_Display_Heat_S2, 377);
    lv_obj_set_align(ui_Display_Heat_S2, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Display_Heat_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Heat_S2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Heat_S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Heat_S2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Heat_S2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Heat_S2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Heat_S2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Heat_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT3 = lv_obj_create(ui_Display_Heat_S2);
    lv_obj_set_width(ui_DT3, lv_pct(50));
    lv_obj_set_height(ui_DT3, lv_pct(100));
    lv_obj_set_align(ui_DT3, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_DT3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Printing_Head_Temp3 = lv_label_create(ui_DT3);
    lv_obj_set_width(ui_Label_Printing_Head_Temp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Printing_Head_Temp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Printing_Head_Temp3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Printing_Head_Temp3, "Head Temp.");
    lv_obj_set_style_text_color(ui_Label_Printing_Head_Temp3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Printing_Head_Temp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Printing_Head_Temp3, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Head_Temp2 = lv_label_create(ui_DT3);
    lv_obj_set_width(ui_Label_Head_Temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Head_Temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Head_Temp2, 40);
    lv_obj_set_y(ui_Label_Head_Temp2, 10);
    lv_obj_set_align(ui_Label_Head_Temp2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Head_Temp2, "195°");
    lv_obj_set_style_text_color(ui_Label_Head_Temp2, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Head_Temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Head_Temp2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Display_Heat_S2);
    lv_obj_set_width(ui_Panel2, 2);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT3_copy3 = lv_obj_create(ui_Display_Heat_S2);
    lv_obj_set_width(ui_DT3_copy3, lv_pct(50));
    lv_obj_set_height(ui_DT3_copy3, lv_pct(100));
    lv_obj_set_align(ui_DT3_copy3, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_DT3_copy3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT3_copy3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT3_copy3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT3_copy3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT3_copy3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT3_copy3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT3_copy3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT3_copy3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT3_copy3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT3_copy3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Printing_Bed_Temp5 = lv_label_create(ui_DT3_copy3);
    lv_obj_set_width(ui_Label_Printing_Bed_Temp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Printing_Bed_Temp5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Printing_Bed_Temp5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Printing_Bed_Temp5, "Bed Temp.");
    lv_obj_set_style_text_color(ui_Label_Printing_Bed_Temp5, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Printing_Bed_Temp5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Printing_Bed_Temp5, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Head2 = lv_image_create(ui_DT3_copy3);
    lv_image_set_src(ui_IMG_Head2, &ui_img_icn_bed_png);
    lv_obj_set_width(ui_IMG_Head2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Head2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Head2, 20);
    lv_obj_set_y(ui_IMG_Head2, 10);
    lv_obj_set_align(ui_IMG_Head2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_Head2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Label_Bed_Temp4 = lv_label_create(ui_DT3_copy3);
    lv_obj_set_width(ui_Label_Bed_Temp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Bed_Temp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Bed_Temp4, 55);
    lv_obj_set_y(ui_Label_Bed_Temp4, 10);
    lv_obj_set_align(ui_Label_Bed_Temp4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Bed_Temp4, "65°");
    lv_obj_set_style_text_color(ui_Label_Bed_Temp4, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Bed_Temp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Bed_Temp4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Printing_Bed_Temp1 = lv_label_create(ui_DT3_copy3);
    lv_obj_set_width(ui_Label_Printing_Bed_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Printing_Bed_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Printing_Bed_Temp1, 100);
    lv_obj_set_y(ui_Label_Printing_Bed_Temp1, 13);
    lv_obj_set_align(ui_Label_Printing_Bed_Temp1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Printing_Bed_Temp1, "/ 65°");
    lv_obj_set_style_text_color(ui_Label_Printing_Bed_Temp1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Printing_Bed_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Printing_Bed_Temp1, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Swich_Group2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Swich_Group2, 160);
    lv_obj_set_height(ui_Swich_Group2, 422);
    lv_obj_set_x(ui_Swich_Group2, -20);
    lv_obj_set_y(ui_Swich_Group2, 50);
    lv_obj_set_align(ui_Swich_Group2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_Swich_Group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Swich_Group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Swich_Group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Swich_Group2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Swich_Group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Light2 = lv_label_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Label_Light2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Light2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Light2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Light2, "MATERIAL");
    lv_obj_set_style_text_color(ui_Label_Light2, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Light2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Light2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Light2, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Light2 = lv_switch_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Switch_Light2, 90);
    lv_obj_set_height(ui_Switch_Light2, 40);
    lv_obj_set_x(ui_Switch_Light2, 0);
    lv_obj_set_y(ui_Switch_Light2, 30);
    lv_obj_set_align(ui_Switch_Light2, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Switch_Light2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Light2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Light2, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Light2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Light2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Light2, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Light2, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Light2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Light2, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Light2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Light2, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Light2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Light2, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Light2, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Light2, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Light2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Light2, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Light2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Light2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Light2, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Light2, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Light2, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Light2, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Light2, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_Switch_Light2, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_Switch_Light2, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Light2, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label_Fan_7 = lv_label_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Label_Fan_7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fan_7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fan_7, 0);
    lv_obj_set_y(ui_Label_Fan_7, 100);
    lv_obj_set_align(ui_Label_Fan_7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Fan_7, "FAN 1");
    lv_obj_set_style_text_color(ui_Label_Fan_7, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fan_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Fan_7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fan_7, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Fan_7 = lv_switch_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Switch_Fan_7, 90);
    lv_obj_set_height(ui_Switch_Fan_7, 40);
    lv_obj_set_x(ui_Switch_Fan_7, 0);
    lv_obj_set_y(ui_Switch_Fan_7, 130);
    lv_obj_set_align(ui_Switch_Fan_7, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Switch_Fan_7, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Fan_7, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Fan_7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Fan_7, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Fan_7, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Fan_7, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_7, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_7, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_7, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Fan_7, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Fan_7, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Fan_7, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Fan_7, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Fan_7, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_7, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Fan_7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Fan_7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_7, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Fan_7, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Fan_7, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Fan_7, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Fan_7, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_Switch_Fan_7, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_Switch_Fan_7, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_7, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label_Fan_4 = lv_label_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Label_Fan_4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fan_4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fan_4, 0);
    lv_obj_set_y(ui_Label_Fan_4, 200);
    lv_obj_set_align(ui_Label_Fan_4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Fan_4, "FAN 2\n");
    lv_obj_set_style_text_color(ui_Label_Fan_4, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fan_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Fan_4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fan_4, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Fan_4 = lv_switch_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Switch_Fan_4, 90);
    lv_obj_set_height(ui_Switch_Fan_4, 40);
    lv_obj_set_x(ui_Switch_Fan_4, 0);
    lv_obj_set_y(ui_Switch_Fan_4, 230);
    lv_obj_set_align(ui_Switch_Fan_4, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Switch_Fan_4, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Fan_4, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Fan_4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Fan_4, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Fan_4, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Fan_4, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_4, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_4, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Fan_4, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Fan_4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Fan_4, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Fan_4, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Fan_4, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_4, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Fan_4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Fan_4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_4, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Fan_4, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Fan_4, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Fan_4, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Fan_4, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_Switch_Fan_4, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_Switch_Fan_4, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_4, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label_Fan_5 = lv_label_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Label_Fan_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Fan_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Fan_5, 0);
    lv_obj_set_y(ui_Label_Fan_5, 300);
    lv_obj_set_align(ui_Label_Fan_5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Fan_5, "FAN 3");
    lv_obj_set_style_text_color(ui_Label_Fan_5, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Fan_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Fan_5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Fan_5, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_Fan_5 = lv_switch_create(ui_Swich_Group2);
    lv_obj_set_width(ui_Switch_Fan_5, 90);
    lv_obj_set_height(ui_Switch_Fan_5, 40);
    lv_obj_set_x(ui_Switch_Fan_5, 0);
    lv_obj_set_y(ui_Switch_Fan_5, 330);
    lv_obj_set_align(ui_Switch_Fan_5, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Switch_Fan_5, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Switch_Fan_5, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch_Fan_5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch_Fan_5, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch_Fan_5, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_Fan_5, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_5, lv_color_hex(0x0179FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_5, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Switch_Fan_5, lv_color_hex(0x191D26), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Switch_Fan_5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Switch_Fan_5, 5, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_Switch_Fan_5, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch_Fan_5, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_Fan_5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch_Fan_5, lv_color_hex(0x536483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch_Fan_5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch_Fan_5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch_Fan_5, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Switch_Fan_5, lv_color_hex(0x00FEFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch_Fan_5, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch_Fan_5, 5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch_Fan_5, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_Switch_Fan_5, -3, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_Switch_Fan_5, 0, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_left(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_right(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_top(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_pad_bottom(ui_Switch_Fan_5, -5, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_BTN_Cancel3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_BTN_Cancel3, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTN_Cancel3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Cancel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BTN_Cancel3, -250);
    lv_obj_set_y(ui_BTN_Cancel3, -111);
    lv_obj_set_align(ui_BTN_Cancel3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BTN_Cancel3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTN_Cancel_Top3 = lv_image_create(ui_BTN_Cancel3);
    lv_image_set_src(ui_BTN_Cancel_Top3, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTN_Cancel_Top3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Cancel_Top3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTN_Cancel_Top3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Cancel_Top3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTN_Cancel_Top3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Cancel_Top3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Cancel_Top3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Cancel_Top3, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTN_Cancel_Top3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTN_Cancel_Top3, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTN_Cancel_Top3, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_BTN_Cancel_Top3, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_BTN_Cancel_Top3, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTN_Cancel_Top3, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Cancel_Top3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Cancel_Top3, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Cancel_Top3, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_BTN_Cancel_Top3, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_BTN_Cancel_Top3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image_Cancel3 = lv_image_create(ui_BTN_Cancel_Top3);
    lv_image_set_src(ui_Image_Cancel3, &ui_img_icn_stop_png);
    lv_obj_set_width(ui_Image_Cancel3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image_Cancel3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image_Cancel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Cancel3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_image_recolor(ui_Image_Cancel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image_Cancel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN_Cancel_Top3, ui_event_BTN_Cancel_Top3, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Display_Heat_S2 = NULL;
    ui_DT3 = NULL;
    ui_Label_Printing_Head_Temp3 = NULL;
    ui_Label_Head_Temp2 = NULL;
    ui_Panel2 = NULL;
    ui_DT3_copy3 = NULL;
    ui_Label_Printing_Bed_Temp5 = NULL;
    ui_IMG_Head2 = NULL;
    ui_Label_Bed_Temp4 = NULL;
    ui_Label_Printing_Bed_Temp1 = NULL;
    ui_Swich_Group2 = NULL;
    ui_Label_Light2 = NULL;
    ui_Switch_Light2 = NULL;
    ui_Label_Fan_7 = NULL;
    ui_Switch_Fan_7 = NULL;
    ui_Label_Fan_4 = NULL;
    ui_Switch_Fan_4 = NULL;
    ui_Label_Fan_5 = NULL;
    ui_Switch_Fan_5 = NULL;
    ui_BTN_Cancel3 = NULL;
    ui_BTN_Cancel_Top3 = NULL;
    ui_Image_Cancel3 = NULL;

}
