// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#include "ui.h"

lv_obj_t * ui_Screen_1_Main = NULL;
lv_obj_t * ui_Background = NULL;
lv_obj_t * ui_Panel_Header = NULL;
lv_obj_t * ui_Label_Header = NULL;
lv_obj_t * ui_BTN_Menu_Print_S1 = NULL;
lv_obj_t * ui_BTN_Menu_Setting_S1 = NULL;
lv_obj_t * ui_Panel_Start_Stop = NULL;
lv_obj_t * ui_Panel_Buttons_Start_Stop = NULL;
lv_obj_t * ui_BTN_Srart_Stop = NULL;
lv_obj_t * ui_BTN_Pause_Top = NULL;
lv_obj_t * ui_Image_Pause = NULL;
lv_obj_t * ui_Panel_Slider2 = NULL;
lv_obj_t * ui_Slider_RPM = NULL;
lv_obj_t * ui_BTN_FIX_Mode = NULL;
lv_obj_t * ui_Label_FIX = NULL;
lv_obj_t * ui_BTN_Slider_mode = NULL;
lv_obj_t * ui_Label_Slider_mode = NULL;
lv_obj_t * ui_BTN_Sweep_Mode = NULL;
lv_obj_t * ui_Label_sweep = NULL;
lv_obj_t * ui_SwitchCompression = NULL;
lv_obj_t * ui_Label_Comression = NULL;
lv_obj_t * ui_Display_StatusMessage = NULL;
lv_obj_t * ui_DT2 = NULL;
lv_obj_t * ui_Labelcurrentrpm = NULL;
lv_obj_t * ui_Display_fix_rpm_set = NULL;
lv_obj_t * ui_DT9 = NULL;
lv_obj_t * ui_Labelfixrpmset = NULL;
lv_obj_t * ui_Label_FIX3 = NULL;
lv_obj_t * ui_btn_fix_rpm_minus = NULL;
lv_obj_t * ui_btn_fix_rpm_up = NULL;
lv_obj_t * ui_Display_step_sweep = NULL;
lv_obj_t * ui_DT4 = NULL;
lv_obj_t * ui_Labelstepsweep = NULL;
lv_obj_t * ui_btn_step_sweep_minus = NULL;
lv_obj_t * ui_btn_step_sweep_plus = NULL;
lv_obj_t * ui_Label_step_sweep5 = NULL;
lv_obj_t * ui_Display_low_sweep = NULL;
lv_obj_t * ui_DT5 = NULL;
lv_obj_t * ui_Label_low_sweep = NULL;
lv_obj_t * ui_btn_low_sweep_minus = NULL;
lv_obj_t * ui_btn_low_sweep_plus = NULL;
lv_obj_t * ui_Label_step_sweep6 = NULL;
lv_obj_t * ui_Display_high_sweep = NULL;
lv_obj_t * ui_DT6 = NULL;
lv_obj_t * ui_Label_high_sweep = NULL;
lv_obj_t * ui_btn_high_sweep_minus = NULL;
lv_obj_t * ui_btn_high_sweep_plus = NULL;
lv_obj_t * ui_Label_step_sweep2 = NULL;
lv_obj_t * ui_Display_rpm_off_compression = NULL;
lv_obj_t * ui_DT7 = NULL;
lv_obj_t * ui_Label_rpm_off_compression = NULL;
lv_obj_t * ui_btn_compression_rpm_minus = NULL;
lv_obj_t * ui_btn_compression_rpm_plus = NULL;
lv_obj_t * ui_Label_step_sweep3 = NULL;
lv_obj_t * ui_LabelSliderRPM = NULL;
lv_obj_t * ui_LabelSliderRPM2 = NULL;
lv_obj_t * ui_BTN_Invers = NULL;
lv_obj_t * ui_Label_invers = NULL;
lv_obj_t * ui_BTN_Cylinder = NULL;
lv_obj_t * ui_Label_Cylinder = NULL;
// event funtions
void ui_event_BTN_Menu_Setting_S1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_2_Setting, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_2_Setting_screen_init);
    }
}

void ui_event_Slider_RPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSliderRPM, target, "   ", "  RPM");
    }
}

void ui_event_BTN_FIX_Mode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_BTN_Slider_mode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BTN_Sweep_Mode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_BTN_Slider_mode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_BTN_Sweep_Mode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_BTN_FIX_Mode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_BTN_Sweep_Mode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_BTN_Slider_mode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_BTN_FIX_Mode, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_Screen_1_Main_screen_init(void)
{
    ui_Screen_1_Main = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen_1_Main, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_1_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background = lv_image_create(ui_Screen_1_Main);
    lv_image_set_src(ui_Background, &ui_img_backgroundlight_png);
    lv_obj_set_width(ui_Background, 800);
    lv_obj_set_height(ui_Background, 480);
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_image_set_inner_align(ui_Background, LV_IMAGE_ALIGN_TILE);

    ui_Panel_Header = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Panel_Header, 665);
    lv_obj_set_height(ui_Panel_Header, 39);
    lv_obj_set_x(ui_Panel_Header, -30);
    lv_obj_set_y(ui_Panel_Header, 0);
    lv_obj_set_align(ui_Panel_Header, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header = lv_label_create(ui_Panel_Header);
    lv_obj_set_width(ui_Label_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header, "");
    lv_obj_set_style_text_color(ui_Label_Header, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Menu_Print_S1 = lv_image_create(ui_Screen_1_Main);
    lv_image_set_src(ui_BTN_Menu_Print_S1, &ui_img_btn_main_png);
    lv_obj_set_width(ui_BTN_Menu_Print_S1, 79);
    lv_obj_set_height(ui_BTN_Menu_Print_S1, 160);
    lv_obj_add_flag(ui_BTN_Menu_Print_S1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_BTN_Menu_Print_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_BTN_Menu_Print_S1, LV_IMAGE_ALIGN_TILE);

    ui_BTN_Menu_Setting_S1 = lv_image_create(ui_Screen_1_Main);
    lv_image_set_src(ui_BTN_Menu_Setting_S1, &ui_img_btn_setting_png);
    lv_obj_set_width(ui_BTN_Menu_Setting_S1, 79);
    lv_obj_set_height(ui_BTN_Menu_Setting_S1, 160);
    lv_obj_set_align(ui_BTN_Menu_Setting_S1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTN_Menu_Setting_S1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_BTN_Menu_Setting_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_BTN_Menu_Setting_S1, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_opa(ui_BTN_Menu_Setting_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Start_Stop = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Panel_Start_Stop, 720);
    lv_obj_set_height(ui_Panel_Start_Stop, 430);
    lv_obj_set_x(ui_Panel_Start_Stop, -3);
    lv_obj_set_y(ui_Panel_Start_Stop, -7);
    lv_obj_set_align(ui_Panel_Start_Stop, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_Panel_Start_Stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Start_Stop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Start_Stop, lv_color_hex(0x2D07E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Start_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Buttons_Start_Stop = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Panel_Buttons_Start_Stop, 168);
    lv_obj_set_height(ui_Panel_Buttons_Start_Stop, 159);
    lv_obj_set_x(ui_Panel_Buttons_Start_Stop, -354);
    lv_obj_set_y(ui_Panel_Buttons_Start_Stop, -219);
    lv_obj_set_align(ui_Panel_Buttons_Start_Stop, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_Panel_Buttons_Start_Stop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Buttons_Start_Stop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Buttons_Start_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Buttons_Start_Stop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Srart_Stop = lv_image_create(ui_Panel_Buttons_Start_Stop);
    lv_image_set_src(ui_BTN_Srart_Stop, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTN_Srart_Stop, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Srart_Stop, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BTN_Srart_Stop, -6);
    lv_obj_set_y(ui_BTN_Srart_Stop, 0);
    lv_obj_set_align(ui_BTN_Srart_Stop, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Srart_Stop, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTN_Pause_Top = lv_image_create(ui_BTN_Srart_Stop);
    lv_image_set_src(ui_BTN_Pause_Top, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTN_Pause_Top, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Pause_Top, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTN_Pause_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Pause_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_radius(ui_BTN_Pause_Top, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Pause_Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Pause_Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Pause_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTN_Pause_Top, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTN_Pause_Top, 9, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTN_Pause_Top, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_x(ui_BTN_Pause_Top, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_offset_y(ui_BTN_Pause_Top, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTN_Pause_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Pause_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Pause_Top, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Pause_Top, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_offset_x(ui_BTN_Pause_Top, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_offset_y(ui_BTN_Pause_Top, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor(ui_BTN_Pause_Top, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_image_recolor_opa(ui_BTN_Pause_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image_Pause = lv_image_create(ui_BTN_Pause_Top);
    lv_image_set_src(ui_Image_Pause, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_Image_Pause, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image_Pause, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image_Pause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Pause, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_image_recolor(ui_Image_Pause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image_Pause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Slider2 = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Panel_Slider2, 713);
    lv_obj_set_height(ui_Panel_Slider2, 70);
    lv_obj_set_x(ui_Panel_Slider2, 69);
    lv_obj_set_y(ui_Panel_Slider2, -158);
    lv_obj_set_align(ui_Panel_Slider2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_bg_color(ui_Panel_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider_RPM = lv_slider_create(ui_Panel_Slider2);
    lv_slider_set_range(ui_Slider_RPM, 0, 6000);
    lv_slider_set_value(ui_Slider_RPM, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_RPM) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_RPM, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_RPM, 647);
    lv_obj_set_height(ui_Slider_RPM, 21);
    lv_obj_set_x(ui_Slider_RPM, 7);
    lv_obj_set_y(ui_Slider_RPM, -5);
    lv_obj_set_align(ui_Slider_RPM, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider_RPM, lv_color_hex(0x222733), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Slider_RPM, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Slider_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Slider_RPM, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Slider_RPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider_RPM, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider_RPM, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider_RPM, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider_RPM, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_RPM, lv_color_hex(0x1DE8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_RPM, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider_RPM, lv_color_hex(0x0962B7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider_RPM, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_RPM, lv_color_hex(0x7689AC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_RPM, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider_RPM, lv_color_hex(0x556483), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider_RPM, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Slider_RPM, &ui_img_pot_slider_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider_RPM, lv_color_hex(0x28DCFD), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider_RPM, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider_RPM, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Slider_RPM, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Slider_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider_RPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider_RPM, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider_RPM,
                                                                                                 lv_obj_get_style_pad_right(ui_Slider_RPM, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BTN_FIX_Mode = lv_imagebutton_create(ui_Screen_1_Main);
    lv_imagebutton_set_src(ui_BTN_FIX_Mode, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_BTN_FIX_Mode, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_FIX_Mode, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_FIX_Mode, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_FIX_Mode, 66);
    lv_obj_set_width(ui_BTN_FIX_Mode, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_FIX_Mode, 99);
    lv_obj_set_y(ui_BTN_FIX_Mode, -162);
    lv_obj_set_align(ui_BTN_FIX_Mode, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_FIX_Mode, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_FIX_Mode, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_FIX_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_FIX_Mode, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_FIX_Mode, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_FIX_Mode, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_FIX_Mode, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_FIX = lv_label_create(ui_BTN_FIX_Mode);
    lv_obj_set_width(ui_Label_FIX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_FIX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_FIX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_FIX, "FIX MODE");
    lv_obj_set_style_text_align(ui_Label_FIX, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_FIX, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Slider_mode = lv_imagebutton_create(ui_Screen_1_Main);
    lv_imagebutton_set_src(ui_BTN_Slider_mode, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Slider_mode, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Slider_mode, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Slider_mode, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Slider_mode, 66);
    lv_obj_set_width(ui_BTN_Slider_mode, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Slider_mode, 99);
    lv_obj_set_y(ui_BTN_Slider_mode, -26);
    lv_obj_set_align(ui_BTN_Slider_mode, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Slider_mode, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Slider_mode, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Slider_mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Slider_mode, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Slider_mode, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Slider_mode, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Slider_mode, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Slider_mode = lv_label_create(ui_BTN_Slider_mode);
    lv_obj_set_width(ui_Label_Slider_mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Slider_mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Slider_mode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Slider_mode, "SLIDER MODE");
    lv_obj_set_style_text_align(ui_Label_Slider_mode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Slider_mode, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Sweep_Mode = lv_imagebutton_create(ui_Screen_1_Main);
    lv_imagebutton_set_src(ui_BTN_Sweep_Mode, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Sweep_Mode, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Sweep_Mode, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Sweep_Mode, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Sweep_Mode, 66);
    lv_obj_set_width(ui_BTN_Sweep_Mode, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Sweep_Mode, 99);
    lv_obj_set_y(ui_BTN_Sweep_Mode, -95);
    lv_obj_set_align(ui_BTN_Sweep_Mode, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Sweep_Mode, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Sweep_Mode, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Sweep_Mode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Sweep_Mode, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Sweep_Mode, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Sweep_Mode, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Sweep_Mode, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_sweep = lv_label_create(ui_BTN_Sweep_Mode);
    lv_obj_set_width(ui_Label_sweep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_sweep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_sweep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_sweep, "SWEEP MODE");
    lv_obj_set_style_text_align(ui_Label_sweep, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_sweep, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchCompression = lv_imagebutton_create(ui_Screen_1_Main);
    lv_imagebutton_set_src(ui_SwitchCompression, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_SwitchCompression, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_SwitchCompression, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_SwitchCompression, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png,
                           NULL);
    lv_obj_set_height(ui_SwitchCompression, 66);
    lv_obj_set_width(ui_SwitchCompression, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_SwitchCompression, 442);
    lv_obj_set_y(ui_SwitchCompression, -162);
    lv_obj_set_align(ui_SwitchCompression, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SwitchCompression, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_SwitchCompression, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SwitchCompression, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SwitchCompression, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_SwitchCompression, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_SwitchCompression, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_SwitchCompression, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Comression = lv_label_create(ui_SwitchCompression);
    lv_obj_set_width(ui_Label_Comression, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Comression, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Comression, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Comression, "COMRESSION");
    lv_obj_set_style_text_align(ui_Label_Comression, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Comression, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_StatusMessage = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Display_StatusMessage, 280);
    lv_obj_set_height(ui_Display_StatusMessage, 87);
    lv_obj_set_x(ui_Display_StatusMessage, -47);
    lv_obj_set_y(ui_Display_StatusMessage, 140);
    lv_obj_set_align(ui_Display_StatusMessage, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Display_StatusMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_StatusMessage, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_StatusMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_StatusMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_StatusMessage, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_StatusMessage, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_StatusMessage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_StatusMessage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT2 = lv_obj_create(ui_Display_StatusMessage);
    lv_obj_set_width(ui_DT2, lv_pct(87));
    lv_obj_set_height(ui_DT2, lv_pct(64));
    lv_obj_set_x(ui_DT2, -3);
    lv_obj_set_y(ui_DT2, -1);
    lv_obj_set_align(ui_DT2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DT2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelcurrentrpm = lv_label_create(ui_Display_StatusMessage);
    lv_obj_set_width(ui_Labelcurrentrpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelcurrentrpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelcurrentrpm, 5);
    lv_obj_set_y(ui_Labelcurrentrpm, -2);
    lv_obj_set_align(ui_Labelcurrentrpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelcurrentrpm, "");
    lv_obj_set_style_text_color(ui_Labelcurrentrpm, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelcurrentrpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelcurrentrpm, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Labelcurrentrpm, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelcurrentrpm, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_fix_rpm_set = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Display_fix_rpm_set, 120);
    lv_obj_set_height(ui_Display_fix_rpm_set, 50);
    lv_obj_set_x(ui_Display_fix_rpm_set, 107);
    lv_obj_set_y(ui_Display_fix_rpm_set, -86);
    lv_obj_set_align(ui_Display_fix_rpm_set, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_Display_fix_rpm_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_fix_rpm_set, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_fix_rpm_set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_fix_rpm_set, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_fix_rpm_set, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_fix_rpm_set, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_fix_rpm_set, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_fix_rpm_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT9 = lv_obj_create(ui_Display_fix_rpm_set);
    lv_obj_set_width(ui_DT9, 95);
    lv_obj_set_height(ui_DT9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DT9, -1);
    lv_obj_set_y(ui_DT9, -1);
    lv_obj_set_align(ui_DT9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DT9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT9, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT9, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT9, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT9, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DT9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelfixrpmset = lv_label_create(ui_DT9);
    lv_obj_set_width(ui_Labelfixrpmset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelfixrpmset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelfixrpmset, -1);
    lv_obj_set_y(ui_Labelfixrpmset, 1);
    lv_obj_set_align(ui_Labelfixrpmset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelfixrpmset, "");
    lv_obj_set_style_text_color(ui_Labelfixrpmset, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelfixrpmset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelfixrpmset, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_FIX3 = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Label_FIX3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_FIX3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_FIX3, -233);
    lv_obj_set_y(ui_Label_FIX3, 91);
    lv_obj_set_align(ui_Label_FIX3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_FIX3, "FIX MODE");
    lv_obj_set_style_text_color(ui_Label_FIX3, lv_color_hex(0x8BA5B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_FIX3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_FIX3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_FIX3, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_fix_rpm_minus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_fix_rpm_minus, 55);
    lv_obj_set_height(ui_btn_fix_rpm_minus, 55);
    lv_obj_set_x(ui_btn_fix_rpm_minus, 108);
    lv_obj_set_y(ui_btn_fix_rpm_minus, -24);
    lv_obj_set_align(ui_btn_fix_rpm_minus, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_fix_rpm_minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_fix_rpm_minus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_fix_rpm_minus, &ui_img_btn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_fix_rpm_up = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_fix_rpm_up, 55);
    lv_obj_set_height(ui_btn_fix_rpm_up, 55);
    lv_obj_set_x(ui_btn_fix_rpm_up, 169);
    lv_obj_set_y(ui_btn_fix_rpm_up, -24);
    lv_obj_set_align(ui_btn_fix_rpm_up, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_btn_fix_rpm_up, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_fix_rpm_up, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_fix_rpm_up, &ui_img_btn_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_step_sweep = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Display_step_sweep, 120);
    lv_obj_set_height(ui_Display_step_sweep, 50);
    lv_obj_set_x(ui_Display_step_sweep, -439);
    lv_obj_set_y(ui_Display_step_sweep, 346);
    lv_obj_set_align(ui_Display_step_sweep, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Display_step_sweep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_step_sweep, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_step_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_step_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_step_sweep, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_step_sweep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_step_sweep, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_step_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT4 = lv_obj_create(ui_Display_step_sweep);
    lv_obj_set_width(ui_DT4, 95);
    lv_obj_set_height(ui_DT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DT4, -1);
    lv_obj_set_y(ui_DT4, -1);
    lv_obj_set_align(ui_DT4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DT4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelstepsweep = lv_label_create(ui_DT4);
    lv_obj_set_width(ui_Labelstepsweep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelstepsweep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelstepsweep, -1);
    lv_obj_set_y(ui_Labelstepsweep, 1);
    lv_obj_set_align(ui_Labelstepsweep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelstepsweep, "");
    lv_obj_set_style_text_color(ui_Labelstepsweep, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelstepsweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelstepsweep, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_step_sweep_minus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_step_sweep_minus, 55);
    lv_obj_set_height(ui_btn_step_sweep_minus, 55);
    lv_obj_set_x(ui_btn_step_sweep_minus, -130);
    lv_obj_set_y(ui_btn_step_sweep_minus, 190);
    lv_obj_set_align(ui_btn_step_sweep_minus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_step_sweep_minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_step_sweep_minus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_step_sweep_minus, &ui_img_btn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_step_sweep_plus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_step_sweep_plus, 55);
    lv_obj_set_height(ui_btn_step_sweep_plus, 55);
    lv_obj_set_x(ui_btn_step_sweep_plus, -69);
    lv_obj_set_y(ui_btn_step_sweep_plus, 190);
    lv_obj_set_align(ui_btn_step_sweep_plus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_step_sweep_plus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_step_sweep_plus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_step_sweep_plus, &ui_img_btn_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_step_sweep5 = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Label_step_sweep5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_step_sweep5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_step_sweep5, -98);
    lv_obj_set_y(ui_Label_step_sweep5, 91);
    lv_obj_set_align(ui_Label_step_sweep5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_step_sweep5, "STEP SWEEP");
    lv_obj_set_style_text_color(ui_Label_step_sweep5, lv_color_hex(0x8BA5B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_step_sweep5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_step_sweep5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_step_sweep5, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_low_sweep = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Display_low_sweep, 120);
    lv_obj_set_height(ui_Display_low_sweep, 50);
    lv_obj_set_x(ui_Display_low_sweep, -304);
    lv_obj_set_y(ui_Display_low_sweep, 346);
    lv_obj_set_align(ui_Display_low_sweep, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Display_low_sweep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_low_sweep, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_low_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_low_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_low_sweep, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_low_sweep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_low_sweep, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_low_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT5 = lv_obj_create(ui_Display_low_sweep);
    lv_obj_set_width(ui_DT5, 95);
    lv_obj_set_height(ui_DT5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DT5, -1);
    lv_obj_set_y(ui_DT5, -1);
    lv_obj_set_align(ui_DT5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DT5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_low_sweep = lv_label_create(ui_DT5);
    lv_obj_set_width(ui_Label_low_sweep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_low_sweep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_low_sweep, -1);
    lv_obj_set_y(ui_Label_low_sweep, 1);
    lv_obj_set_align(ui_Label_low_sweep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_low_sweep, "");
    lv_obj_set_style_text_color(ui_Label_low_sweep, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_low_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_low_sweep, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_low_sweep_minus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_low_sweep_minus, 55);
    lv_obj_set_height(ui_btn_low_sweep_minus, 55);
    lv_obj_set_x(ui_btn_low_sweep_minus, 4);
    lv_obj_set_y(ui_btn_low_sweep_minus, 190);
    lv_obj_set_align(ui_btn_low_sweep_minus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_low_sweep_minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_low_sweep_minus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_low_sweep_minus, &ui_img_btn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_low_sweep_plus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_low_sweep_plus, 55);
    lv_obj_set_height(ui_btn_low_sweep_plus, 55);
    lv_obj_set_x(ui_btn_low_sweep_plus, 66);
    lv_obj_set_y(ui_btn_low_sweep_plus, 190);
    lv_obj_set_align(ui_btn_low_sweep_plus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_low_sweep_plus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_low_sweep_plus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_low_sweep_plus, &ui_img_btn_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_step_sweep6 = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Label_step_sweep6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_step_sweep6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_step_sweep6, 36);
    lv_obj_set_y(ui_Label_step_sweep6, 91);
    lv_obj_set_align(ui_Label_step_sweep6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_step_sweep6, "LOW SWEEP");
    lv_obj_set_style_text_color(ui_Label_step_sweep6, lv_color_hex(0x8BA5B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_step_sweep6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_step_sweep6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_step_sweep6, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_high_sweep = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Display_high_sweep, 120);
    lv_obj_set_height(ui_Display_high_sweep, 50);
    lv_obj_set_x(ui_Display_high_sweep, -172);
    lv_obj_set_y(ui_Display_high_sweep, 346);
    lv_obj_set_align(ui_Display_high_sweep, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Display_high_sweep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_high_sweep, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_high_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_high_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_high_sweep, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_high_sweep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_high_sweep, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_high_sweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT6 = lv_obj_create(ui_Display_high_sweep);
    lv_obj_set_width(ui_DT6, 95);
    lv_obj_set_height(ui_DT6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DT6, -1);
    lv_obj_set_y(ui_DT6, -1);
    lv_obj_set_align(ui_DT6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DT6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT6, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT6, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT6, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT6, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_high_sweep = lv_label_create(ui_DT6);
    lv_obj_set_width(ui_Label_high_sweep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_high_sweep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_high_sweep, -1);
    lv_obj_set_y(ui_Label_high_sweep, 1);
    lv_obj_set_align(ui_Label_high_sweep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_high_sweep, "");
    lv_obj_set_style_text_color(ui_Label_high_sweep, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_high_sweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_high_sweep, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_high_sweep_minus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_high_sweep_minus, 55);
    lv_obj_set_height(ui_btn_high_sweep_minus, 55);
    lv_obj_set_x(ui_btn_high_sweep_minus, 134);
    lv_obj_set_y(ui_btn_high_sweep_minus, 190);
    lv_obj_set_align(ui_btn_high_sweep_minus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_high_sweep_minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_high_sweep_minus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_high_sweep_minus, &ui_img_btn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_high_sweep_plus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_high_sweep_plus, 55);
    lv_obj_set_height(ui_btn_high_sweep_plus, 55);
    lv_obj_set_x(ui_btn_high_sweep_plus, 196);
    lv_obj_set_y(ui_btn_high_sweep_plus, 190);
    lv_obj_set_align(ui_btn_high_sweep_plus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_high_sweep_plus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_high_sweep_plus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_high_sweep_plus, &ui_img_btn_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_step_sweep2 = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Label_step_sweep2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_step_sweep2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_step_sweep2, 166);
    lv_obj_set_y(ui_Label_step_sweep2, 91);
    lv_obj_set_align(ui_Label_step_sweep2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_step_sweep2, "HIGH SWEEP");
    lv_obj_set_style_text_color(ui_Label_step_sweep2, lv_color_hex(0x8BA5B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_step_sweep2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_step_sweep2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_step_sweep2, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_rpm_off_compression = lv_obj_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Display_rpm_off_compression, 120);
    lv_obj_set_height(ui_Display_rpm_off_compression, 50);
    lv_obj_set_x(ui_Display_rpm_off_compression, -40);
    lv_obj_set_y(ui_Display_rpm_off_compression, 346);
    lv_obj_set_align(ui_Display_rpm_off_compression, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Display_rpm_off_compression, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_rpm_off_compression, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_rpm_off_compression, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_rpm_off_compression, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_rpm_off_compression, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_rpm_off_compression, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_rpm_off_compression, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_rpm_off_compression, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DT7 = lv_obj_create(ui_Display_rpm_off_compression);
    lv_obj_set_width(ui_DT7, 95);
    lv_obj_set_height(ui_DT7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DT7, -1);
    lv_obj_set_y(ui_DT7, -1);
    lv_obj_set_align(ui_DT7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DT7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DT7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DT7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DT7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DT7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DT7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DT7, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DT7, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DT7, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DT7, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_rpm_off_compression = lv_label_create(ui_DT7);
    lv_obj_set_width(ui_Label_rpm_off_compression, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_rpm_off_compression, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_rpm_off_compression, -1);
    lv_obj_set_y(ui_Label_rpm_off_compression, 1);
    lv_obj_set_align(ui_Label_rpm_off_compression, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_rpm_off_compression, "");
    lv_obj_set_style_text_color(ui_Label_rpm_off_compression, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_rpm_off_compression, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_rpm_off_compression, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_compression_rpm_minus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_compression_rpm_minus, 55);
    lv_obj_set_height(ui_btn_compression_rpm_minus, 55);
    lv_obj_set_x(ui_btn_compression_rpm_minus, 270);
    lv_obj_set_y(ui_btn_compression_rpm_minus, 190);
    lv_obj_set_align(ui_btn_compression_rpm_minus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_compression_rpm_minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_compression_rpm_minus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_compression_rpm_minus, &ui_img_btn_minus_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_compression_rpm_plus = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_btn_compression_rpm_plus, 55);
    lv_obj_set_height(ui_btn_compression_rpm_plus, 55);
    lv_obj_set_x(ui_btn_compression_rpm_plus, 332);
    lv_obj_set_y(ui_btn_compression_rpm_plus, 190);
    lv_obj_set_align(ui_btn_compression_rpm_plus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_compression_rpm_plus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn_compression_rpm_plus, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_btn_compression_rpm_plus, &ui_img_btn_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_step_sweep3 = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_Label_step_sweep3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_step_sweep3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_step_sweep3, 301);
    lv_obj_set_y(ui_Label_step_sweep3, 91);
    lv_obj_set_align(ui_Label_step_sweep3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_step_sweep3, "COMPR OFF");
    lv_obj_set_style_text_color(ui_Label_step_sweep3, lv_color_hex(0x8BA5B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_step_sweep3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_step_sweep3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_step_sweep3, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSliderRPM = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_LabelSliderRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSliderRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSliderRPM, -52);
    lv_obj_set_y(ui_LabelSliderRPM, 11);
    lv_obj_set_align(ui_LabelSliderRPM, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelSliderRPM, "RPM");
    lv_obj_set_style_text_color(ui_LabelSliderRPM, lv_color_hex(0xBFCAD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSliderRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSliderRPM, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSliderRPM, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSliderRPM2 = lv_label_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_LabelSliderRPM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSliderRPM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSliderRPM2, 179);
    lv_obj_set_y(ui_LabelSliderRPM2, 12);
    lv_obj_set_align(ui_LabelSliderRPM2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSliderRPM2, "SLIDER SET ");
    lv_obj_set_style_text_color(ui_LabelSliderRPM2, lv_color_hex(0xBFCAD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSliderRPM2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSliderRPM2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Invers = lv_imagebutton_create(ui_Screen_1_Main);
    lv_imagebutton_set_src(ui_BTN_Invers, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Invers, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Invers, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imagebutton_set_src(ui_BTN_Invers, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Invers, 65);
    lv_obj_set_width(ui_BTN_Invers, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_x(ui_BTN_Invers, 270);
    lv_obj_set_y(ui_BTN_Invers, -162);
    lv_obj_set_align(ui_BTN_Invers, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Invers, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Invers, lv_color_hex(0xBFCAD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Invers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Invers, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Invers, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Invers, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Invers, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_invers = lv_label_create(ui_BTN_Invers);
    lv_obj_set_width(ui_Label_invers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_invers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_invers, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_invers, "");
    lv_obj_set_style_text_align(ui_Label_invers, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_invers, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Cylinder = lv_button_create(ui_Screen_1_Main);
    lv_obj_set_width(ui_BTN_Cylinder, 145);
    lv_obj_set_height(ui_BTN_Cylinder, 50);
    lv_obj_set_x(ui_BTN_Cylinder, 293);
    lv_obj_set_y(ui_BTN_Cylinder, -162);
    lv_obj_set_align(ui_BTN_Cylinder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Cylinder, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTN_Cylinder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTN_Cylinder, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Cylinder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Cylinder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Cylinder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Cylinder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BTN_Cylinder, &ui_img_btn_main_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Cylinder = lv_label_create(ui_BTN_Cylinder);
    lv_obj_set_width(ui_Label_Cylinder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Cylinder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Cylinder, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Cylinder, "CYLINDER");
    lv_obj_set_style_text_color(ui_Label_Cylinder, lv_color_hex(0xA7BEDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Cylinder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Cylinder, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Cylinder, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN_Menu_Setting_S1, ui_event_BTN_Menu_Setting_S1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider_RPM, ui_event_Slider_RPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_FIX_Mode, ui_event_BTN_FIX_Mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Slider_mode, ui_event_BTN_Slider_mode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Sweep_Mode, ui_event_BTN_Sweep_Mode, LV_EVENT_ALL, NULL);

}

void ui_Screen_1_Main_screen_destroy(void)
{
    if(ui_Screen_1_Main) lv_obj_del(ui_Screen_1_Main);

    // NULL screen variables
    ui_Screen_1_Main = NULL;
    ui_Background = NULL;
    ui_Panel_Header = NULL;
    ui_Label_Header = NULL;
    ui_BTN_Menu_Print_S1 = NULL;
    ui_BTN_Menu_Setting_S1 = NULL;
    ui_Panel_Start_Stop = NULL;
    ui_Panel_Buttons_Start_Stop = NULL;
    ui_BTN_Srart_Stop = NULL;
    ui_BTN_Pause_Top = NULL;
    ui_Image_Pause = NULL;
    ui_Panel_Slider2 = NULL;
    ui_Slider_RPM = NULL;
    ui_BTN_FIX_Mode = NULL;
    ui_Label_FIX = NULL;
    ui_BTN_Slider_mode = NULL;
    ui_Label_Slider_mode = NULL;
    ui_BTN_Sweep_Mode = NULL;
    ui_Label_sweep = NULL;
    ui_SwitchCompression = NULL;
    ui_Label_Comression = NULL;
    ui_Display_StatusMessage = NULL;
    ui_DT2 = NULL;
    ui_Labelcurrentrpm = NULL;
    ui_Display_fix_rpm_set = NULL;
    ui_DT9 = NULL;
    ui_Labelfixrpmset = NULL;
    ui_Label_FIX3 = NULL;
    ui_btn_fix_rpm_minus = NULL;
    ui_btn_fix_rpm_up = NULL;
    ui_Display_step_sweep = NULL;
    ui_DT4 = NULL;
    ui_Labelstepsweep = NULL;
    ui_btn_step_sweep_minus = NULL;
    ui_btn_step_sweep_plus = NULL;
    ui_Label_step_sweep5 = NULL;
    ui_Display_low_sweep = NULL;
    ui_DT5 = NULL;
    ui_Label_low_sweep = NULL;
    ui_btn_low_sweep_minus = NULL;
    ui_btn_low_sweep_plus = NULL;
    ui_Label_step_sweep6 = NULL;
    ui_Display_high_sweep = NULL;
    ui_DT6 = NULL;
    ui_Label_high_sweep = NULL;
    ui_btn_high_sweep_minus = NULL;
    ui_btn_high_sweep_plus = NULL;
    ui_Label_step_sweep2 = NULL;
    ui_Display_rpm_off_compression = NULL;
    ui_DT7 = NULL;
    ui_Label_rpm_off_compression = NULL;
    ui_btn_compression_rpm_minus = NULL;
    ui_btn_compression_rpm_plus = NULL;
    ui_Label_step_sweep3 = NULL;
    ui_LabelSliderRPM = NULL;
    ui_LabelSliderRPM2 = NULL;
    ui_BTN_Invers = NULL;
    ui_Label_invers = NULL;
    ui_BTN_Cylinder = NULL;
    ui_Label_Cylinder = NULL;

}
