// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#ifndef UI_SCREEN_1_MAIN_H
#define UI_SCREEN_1_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_1_Main
extern void ui_Screen_1_Main_screen_init(void);
extern void ui_Screen_1_Main_screen_destroy(void);
extern lv_obj_t * ui_Screen_1_Main;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_Panel_Header;
extern lv_obj_t * ui_Label_Header;
extern lv_obj_t * ui_BTN_Menu_Print_S1;
extern void ui_event_BTN_Menu_Setting_S1(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Setting_S1;
extern lv_obj_t * ui_Panel_Start_Stop;
extern lv_obj_t * ui_Panel_Buttons_Start_Stop;
extern lv_obj_t * ui_BTN_Srart_Stop;
extern lv_obj_t * ui_BTN_Pause_Top;
extern lv_obj_t * ui_Image_Pause;
extern lv_obj_t * ui_Panel_Slider2;
extern void ui_event_Slider_RPM(lv_event_t * e);
extern lv_obj_t * ui_Slider_RPM;
extern void ui_event_BTN_FIX_Mode(lv_event_t * e);
extern lv_obj_t * ui_BTN_FIX_Mode;
extern lv_obj_t * ui_Label_FIX;
extern void ui_event_BTN_Slider_mode(lv_event_t * e);
extern lv_obj_t * ui_BTN_Slider_mode;
extern lv_obj_t * ui_Label_Slider_mode;
extern void ui_event_BTN_Sweep_Mode(lv_event_t * e);
extern lv_obj_t * ui_BTN_Sweep_Mode;
extern lv_obj_t * ui_Label_sweep;
extern lv_obj_t * ui_SwitchCompression;
extern lv_obj_t * ui_Label_Comression;
extern lv_obj_t * ui_Display_StatusMessage;
extern lv_obj_t * ui_DT2;
extern lv_obj_t * ui_Labelcurrentrpm;
extern lv_obj_t * ui_Display_fix_rpm_set;
extern lv_obj_t * ui_DT9;
extern lv_obj_t * ui_Labelfixrpmset;
extern lv_obj_t * ui_Label_FIX3;
extern lv_obj_t * ui_btn_fix_rpm_minus;
extern lv_obj_t * ui_btn_fix_rpm_up;
extern lv_obj_t * ui_Display_step_sweep;
extern lv_obj_t * ui_DT4;
extern lv_obj_t * ui_Labelstepsweep;
extern lv_obj_t * ui_btn_step_sweep_minus;
extern lv_obj_t * ui_btn_step_sweep_plus;
extern lv_obj_t * ui_Label_step_sweep5;
extern lv_obj_t * ui_Display_low_sweep;
extern lv_obj_t * ui_DT5;
extern lv_obj_t * ui_Label_low_sweep;
extern lv_obj_t * ui_btn_low_sweep_minus;
extern lv_obj_t * ui_btn_low_sweep_plus;
extern lv_obj_t * ui_Label_step_sweep6;
extern lv_obj_t * ui_Display_high_sweep;
extern lv_obj_t * ui_DT6;
extern lv_obj_t * ui_Label_high_sweep;
extern lv_obj_t * ui_btn_high_sweep_minus;
extern lv_obj_t * ui_btn_high_sweep_plus;
extern lv_obj_t * ui_Label_step_sweep2;
extern lv_obj_t * ui_Display_rpm_off_compression;
extern lv_obj_t * ui_DT7;
extern lv_obj_t * ui_Label_rpm_off_compression;
extern lv_obj_t * ui_btn_compression_rpm_minus;
extern lv_obj_t * ui_btn_compression_rpm_plus;
extern lv_obj_t * ui_Label_step_sweep3;
extern lv_obj_t * ui_LabelSliderRPM;
extern lv_obj_t * ui_LabelSliderRPM2;
extern lv_obj_t * ui_BTN_Invers;
extern lv_obj_t * ui_Label_invers;
extern lv_obj_t * ui_BTN_Cylinder;
extern lv_obj_t * ui_Label_Cylinder;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

