// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Display_Heat_S2;
extern lv_obj_t * ui_DT3;
extern lv_obj_t * ui_Label_Printing_Head_Temp3;
extern lv_obj_t * ui_Label_Head_Temp2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_DT3_copy3;
extern lv_obj_t * ui_Label_Printing_Bed_Temp5;
extern lv_obj_t * ui_IMG_Head2;
extern lv_obj_t * ui_Label_Bed_Temp4;
extern lv_obj_t * ui_Label_Printing_Bed_Temp1;
extern lv_obj_t * ui_Swich_Group2;
extern lv_obj_t * ui_Label_Light2;
extern lv_obj_t * ui_Switch_Light2;
extern lv_obj_t * ui_Label_Fan_7;
extern lv_obj_t * ui_Switch_Fan_7;
extern lv_obj_t * ui_Label_Fan_4;
extern lv_obj_t * ui_Switch_Fan_4;
extern lv_obj_t * ui_Label_Fan_5;
extern lv_obj_t * ui_Switch_Fan_5;
extern lv_obj_t * ui_BTN_Cancel3;
extern void ui_event_BTN_Cancel_Top3(lv_event_t * e);
extern lv_obj_t * ui_BTN_Cancel_Top3;
extern lv_obj_t * ui_Image_Cancel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

