// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#include "ui.h"

lv_obj_t * ui_Screen_2_Setting = NULL;
lv_obj_t * ui_Background2 = NULL;
lv_obj_t * ui_Panel_Header2 = NULL;
lv_obj_t * ui_Label_Header2 = NULL;
lv_obj_t * ui_BTN_Menu_Print_S3 = NULL;
lv_obj_t * ui_BTN_Menu_Setting_S3 = NULL;
lv_obj_t * ui_S1_Content_Panel2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_TextAreaInfo = NULL;
lv_obj_t * ui_Dropdown_Pattern = NULL;
// event funtions
void ui_event_BTN_Menu_Print_S3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_1_Main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_1_Main_screen_init);
    }
}

// build funtions

void ui_Screen_2_Setting_screen_init(void)
{
    ui_Screen_2_Setting = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen_2_Setting, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_2_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background2 = lv_image_create(ui_Screen_2_Setting);
    lv_image_set_src(ui_Background2, &ui_img_backgroundlight_png);
    lv_obj_set_width(ui_Background2, 800);
    lv_obj_set_height(ui_Background2, 480);
    lv_obj_set_align(ui_Background2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_image_set_inner_align(ui_Background2, LV_IMAGE_ALIGN_TILE);

    ui_Panel_Header2 = lv_obj_create(ui_Screen_2_Setting);
    lv_obj_set_width(ui_Panel_Header2, 665);
    lv_obj_set_height(ui_Panel_Header2, 39);
    lv_obj_set_x(ui_Panel_Header2, -30);
    lv_obj_set_y(ui_Panel_Header2, 0);
    lv_obj_set_align(ui_Panel_Header2, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Panel_Header2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header2 = lv_label_create(ui_Panel_Header2);
    lv_obj_set_width(ui_Label_Header2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header2, "");
    lv_obj_set_style_text_color(ui_Label_Header2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header2, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Menu_Print_S3 = lv_obj_create(ui_Screen_2_Setting);
    lv_obj_set_width(ui_BTN_Menu_Print_S3, 79);
    lv_obj_set_height(ui_BTN_Menu_Print_S3, 160);
    lv_obj_remove_flag(ui_BTN_Menu_Print_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_BTN_Menu_Print_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Menu_Print_S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BTN_Menu_Print_S3, &ui_img_btn_main_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Menu_Print_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_Menu_Print_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Menu_Setting_S3 = lv_obj_create(ui_Screen_2_Setting);
    lv_obj_set_width(ui_BTN_Menu_Setting_S3, 79);
    lv_obj_set_height(ui_BTN_Menu_Setting_S3, 160);
    lv_obj_set_align(ui_BTN_Menu_Setting_S3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_BTN_Menu_Setting_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_BTN_Menu_Setting_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Menu_Setting_S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BTN_Menu_Setting_S3, &ui_img_btn_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Menu_Setting_S3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1_Content_Panel2 = lv_obj_create(ui_Screen_2_Setting);
    lv_obj_set_width(ui_S1_Content_Panel2, 720);
    lv_obj_set_height(ui_S1_Content_Panel2, 430);
    lv_obj_set_align(ui_S1_Content_Panel2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_S1_Content_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen_2_Setting);
    lv_image_set_src(ui_Image2, &ui_img_noimage_png);
    lv_obj_set_width(ui_Image2, 680);
    lv_obj_set_height(ui_Image2, 180);
    lv_obj_set_x(ui_Image2, 35);
    lv_obj_set_y(ui_Image2, -30);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Image2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Image2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Image2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Image2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen_2_Setting);
    lv_obj_set_width(ui_Panel3, 50);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, -2006);
    lv_obj_set_y(ui_Panel3, -118);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Panel3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x004400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaInfo = lv_textarea_create(ui_Screen_2_Setting);
    lv_obj_set_width(ui_TextAreaInfo, 688);
    lv_obj_set_height(ui_TextAreaInfo, 154);
    lv_obj_set_x(ui_TextAreaInfo, 37);
    lv_obj_set_y(ui_TextAreaInfo, 154);
    lv_obj_set_align(ui_TextAreaInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TextAreaInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TextAreaInfo, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_TextAreaInfo, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_TextAreaInfo, lv_color_hex(0x060606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaInfo, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaInfo, lv_color_hex(0x647CAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TextAreaInfo, lv_color_hex(0x6D8FD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextAreaInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextAreaInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextAreaInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextAreaInfo, lv_color_hex(0x131212), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaInfo, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaInfo, LV_TEXT_ALIGN_LEFT, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaInfo, &ui_font_Font2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TextAreaInfo, lv_color_hex(0x87A9F4), LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_TextAreaInfo, lv_color_hex(0x87A9F4), LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextAreaInfo, lv_color_hex(0x0A0A0A), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaInfo, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaInfo, &ui_font_Font1, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Dropdown_Pattern = lv_dropdown_create(ui_Screen_2_Setting);
    lv_dropdown_set_options(ui_Dropdown_Pattern, "Pattern");
    lv_obj_set_width(ui_Dropdown_Pattern, 686);
    lv_obj_set_height(ui_Dropdown_Pattern, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_Pattern, 34);
    lv_obj_set_y(ui_Dropdown_Pattern, -164);
    lv_obj_set_align(ui_Dropdown_Pattern, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_Pattern, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Dropdown_Pattern,
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_Pattern, lv_color_hex(0xBFCAD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_Pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown_Pattern, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_Pattern, lv_color_hex(0x647CAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_Pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown_Pattern, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown_Pattern, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown_Pattern, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdown_Pattern, &lv_font_montserrat_18, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown_Pattern), &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown_Pattern), &lv_font_montserrat_18,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN_Menu_Print_S3, ui_event_BTN_Menu_Print_S3, LV_EVENT_ALL, NULL);

}

void ui_Screen_2_Setting_screen_destroy(void)
{
    if(ui_Screen_2_Setting) lv_obj_del(ui_Screen_2_Setting);

    // NULL screen variables
    ui_Screen_2_Setting = NULL;
    ui_Background2 = NULL;
    ui_Panel_Header2 = NULL;
    ui_Label_Header2 = NULL;
    ui_BTN_Menu_Print_S3 = NULL;
    ui_BTN_Menu_Setting_S3 = NULL;
    ui_S1_Content_Panel2 = NULL;
    ui_Image2 = NULL;
    ui_Panel3 = NULL;
    ui_TextAreaInfo = NULL;
    ui_Dropdown_Pattern = NULL;

}
