// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: new

#ifndef UI_SCREEN_2_SETTING_H
#define UI_SCREEN_2_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_2_Setting
extern void ui_Screen_2_Setting_screen_init(void);
extern void ui_Screen_2_Setting_screen_destroy(void);
extern lv_obj_t * ui_Screen_2_Setting;
extern lv_obj_t * ui_Background2;
extern lv_obj_t * ui_Panel_Header2;
extern lv_obj_t * ui_Label_Header2;
extern void ui_event_BTN_Menu_Print_S3(lv_event_t * e);
extern lv_obj_t * ui_BTN_Menu_Print_S3;
extern lv_obj_t * ui_BTN_Menu_Setting_S3;
extern lv_obj_t * ui_S1_Content_Panel2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_TextAreaInfo;
extern lv_obj_t * ui_Dropdown_Pattern;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

